require VERSION file before run

diff --git a/.github/workflows/go-pkg-autorelease.yml b/.github/workflows/go-pkg-autorelease.yml
--- a/.github/workflows/go-pkg-autorelease.yml
+++ b/.github/workflows/go-pkg-autorelease.yml
@@ -14,6 +14,12 @@ jobs:
 
     - uses: actions/checkout@v7
 
+    - name: Check if VERSION file exists
+      run: |
+          if [ ! -f "VERSION" ]; then
+            echo "::error file=VERSION::Error: File 'VERSION' not found in repository root"
+            exit 1
+          fi
     - name: Set and show version number
       run: |
         VERSION=$(cat VERSION)
